# Generated by Django 5.2.17 on 2026-09-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. B.Tech, M.Tech, MBA', max_length=100)),
                ('code', models.CharField(help_text='e.g. BTECH, MTECH, MBA', max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='DailyMessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, unique=True)),
                ('breakfast', models.TextField(help_text='Items served during Breakfast')),
                ('lunch', models.TextField(help_text='Items served during Lunch')),
                ('hi_tea', models.TextField(help_text='Items served during Evening Tea/Snacks')),
                ('dinner', models.TextField(help_text='Items served during Dinner')),
            ],
            options={
                'verbose_name': 'Daily Mess Menu',
                'verbose_name_plural': 'Hostel Mess Menus',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User Name', max_length=100)),
                ('category', models.CharField(choices=[('BUG', 'Bug Report'), ('IDEA', 'Suggestion / Idea'), ('OTHER', 'General Feedback')], default='BUG', max_length=20)),
                ('message', models.TextField(help_text='User Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the module', max_length=100)),
                ('code', models.CharField(help_text='e.g. DSA01, CN01', max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Pooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. A, B, C', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Computer Science & Engineering', max_length=100)),
                ('code', models.CharField(help_text='e.g. CSE, CSE-AIML, ECE, EE, IT, ME, CE', max_length=20, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='blog.course')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(blank=True, help_text='e.g. AR(PH), BA(M), RKA(PH)', max_length=30, null=True)),
                ('designation', models.CharField(choices=[('HOD', 'Head of Department'), ('PROF', 'Professor'), ('ASSOC_PROF', 'Associate Professor'), ('ASST_PROF', 'Assistant Professor'), ('STAFF', 'Supporting Staff')], default='ASST_PROF', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='blog.branch')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InductionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='e.g. 1, 2, 3... 21')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('topic_programme', models.CharField(help_text='e.g. AI & Next Generation, Universal Human Values', max_length=255)),
                ('assigned_persons_text', models.CharField(blank=True, help_text='Text representation of speakers', max_length=255, null=True)),
                ('external_guest', models.CharField(blank=True, help_text='Any external speaker name', max_length=200, null=True)),
                ('venue', models.CharField(default='CSE Seminar Hall', max_length=150)),
                ('material_file', models.FileField(blank=True, help_text='Upload session PDF or PPT presentation', null=True, upload_to='induction_materials/')),
                ('assigned_faculty', models.ManyToManyField(blank=True, related_name='induction_sessions', to='blog.faculty')),
                ('branches_applicable', models.ManyToManyField(blank=True, help_text='Applicable for specific or all branches', to='blog.branch')),
            ],
            options={
                'verbose_name': 'Induction Program Session',
                'verbose_name_plural': 'Induction Program Schedule',
                'ordering': ['day_number', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MessTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('HI_TEA', 'Evening Hi-Tea'), ('DINNER', 'Dinner')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_years', models.ManyToManyField(help_text='Select 1st & 2nd Year OR 3rd & 4th Year', to='blog.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lh_room', models.CharField(help_text='e.g. LH-234, LH-232, LH-231, LH-233, LH-235, LH-236', max_length=50)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('slot_number', models.IntegerField(help_text='Slot 1-9')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject_code', models.CharField(help_text='e.g. BS-PH 101, ES-EE 101, Induction Program', max_length=100)),
                ('subject_name', models.CharField(blank=True, help_text='Full subject name if any', max_length=150, null=True)),
                ('faculty_code', models.CharField(blank=True, help_text='e.g. AR(PH), BA(M), NF(EE)', max_length=100, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_slots', to='blog.branch')),
                ('faculty_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_slots', to='blog.faculty')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_slots', to='blog.academicyear')),
                ('section_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_slots', to='blog.section')),
            ],
            options={
                'verbose_name': 'Class Routine Slot',
                'verbose_name_plural': 'Class Routine Timetable',
                'ordering': ['section_name', 'day', 'slot_number'],
            },
        ),
        migrations.CreateModel(
            name='CRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='CR Name', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_profiles', to='blog.branch')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_profiles', to='blog.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_profiles', to='blog.section')),
            ],
            options={
                'verbose_name_plural': 'Class Representative Profiles',
                'ordering': ['branch', 'section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the subject', max_length=200)),
                ('code', models.CharField(help_text='e.g. DSA, CN, DBMS', max_length=20, unique=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='blog.module')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the notes', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the notes')),
                ('file', models.FileField(help_text='Upload the notes file (PDF, DOCX, etc.)', upload_to='notes_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blog.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blog.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blog.module')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blog.academicyear')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blog.section')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blog.subject')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
