# Generated by Django 5.2.17 on 2026-08-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Computer Science & Engineering', max_length=100)),
                ('code', models.CharField(help_text='e.g. CSE, CSE-AIML, ECE, ME, CE', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, unique=True)),
                ('breakfast', models.TextField(help_text='Items served during Breakfast')),
                ('lunch', models.TextField(help_text='Items served during Lunch')),
                ('hi_tea', models.TextField(help_text='Items served during Evening Tea/Snacks')),
                ('dinner', models.TextField(help_text='Items served during Dinner')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_code', models.CharField(blank=True, help_text='e.g. AR(PH), BA(M)', max_length=20, null=True)),
                ('designation', models.CharField(choices=[('HOD', 'Head of Department'), ('PROF', 'Professor'), ('ASSOC_PROF', 'Associate Professor'), ('ASST_PROF', 'Assistant Professor'), ('STAFF', 'Supporting Staff')], default='ASST_PROF', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='blog.branch')),
            ],
        ),
        migrations.CreateModel(
            name='InductionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='e.g. Day 1, Day 2...')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('topic_programme', models.CharField(help_text='e.g. AI & Next Generation, Universal Human Values', max_length=255)),
                ('external_guest', models.CharField(blank=True, help_text='Any external speaker name', max_length=200, null=True)),
                ('venue', models.CharField(default='CSE Seminar Hall', max_length=150)),
                ('assigned_faculty', models.ManyToManyField(blank=True, related_name='induction_sessions', to='blog.faculty')),
                ('branches_applicable', models.ManyToManyField(blank=True, help_text='Applicable for specific or all branches', to='blog.branch')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='MessTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('HI_TEA', 'Evening Hi-Tea'), ('DINNER', 'Dinner')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_years', models.ManyToManyField(help_text='Select 1st & 2nd Year OR 3rd & 4th Year', to='blog.academicyear')),
            ],
        ),
    ]
