# Generated by Django 5.0.1 on 2026-08-29 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='dailymessmenu',
            options={'verbose_name': 'Daily Mess Menu', 'verbose_name_plural': 'Hostel Mess Menus'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['name'], 'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='inductionprogram',
            options={'ordering': ['day_number', 'start_time'], 'verbose_name': 'Induction Program Session', 'verbose_name_plural': 'Induction Program Schedule'},
        ),
        migrations.AddField(
            model_name='inductionprogram',
            name='assigned_persons_text',
            field=models.CharField(blank=True, help_text='Text representation of speakers', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='e.g. CSE, CSE-AIML, ECE, EE, IT, ME, CE', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='short_code',
            field=models.CharField(blank=True, help_text='e.g. AR(PH), BA(M), RKA(PH)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inductionprogram',
            name='day_number',
            field=models.IntegerField(help_text='e.g. 1, 2, 3... 21'),
        ),
        migrations.CreateModel(
            name='RoutineSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='e.g. CSE 1st SEM (A), CSE (AIML) 1st SEM', max_length=100)),
                ('lh_room', models.CharField(help_text='e.g. LH-234, LH-232, LH-231, LH-233, LH-235, LH-236', max_length=50)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('slot_number', models.IntegerField(help_text='Slot 1-9')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject_code', models.CharField(help_text='e.g. BS-PH 101, ES-EE 101, Induction Program', max_length=100)),
                ('subject_name', models.CharField(blank=True, help_text='Full subject name if any', max_length=150, null=True)),
                ('faculty_code', models.CharField(blank=True, help_text='e.g. AR(PH), BA(M), NF(EE)', max_length=100, null=True)),
                ('faculty_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_slots', to='blog.faculty')),
            ],
            options={
                'verbose_name': 'Class Routine Slot',
                'verbose_name_plural': 'Class Routine Timetable',
                'ordering': ['section_name', 'day', 'slot_number'],
            },
        ),
    ]
