# Generated by Django 5.2.17 on 2026-09-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='module',
        ),
    ]
