# Generated by Django 5.0.1 on 2026-08-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_branch_options_alter_dailymessmenu_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionprogram',
            name='material_file',
            field=models.FileField(blank=True, help_text='Upload session PDF or PPT presentation', null=True, upload_to='induction_materials/'),
        ),
    ]
