# Generated by Django 5.0.1 on 2026-09-13 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_subject_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='cr',
            field=models.ForeignKey(blank=True, help_text='CR who provided this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='blog.crprofile'),
        ),
        migrations.AddField(
            model_name='notes',
            name='cr_name',
            field=models.CharField(blank=True, help_text='CR / Author Name e.g. Rishabh Kumar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(blank=True, help_text='Upload the notes file (PDF, DOCX, etc.)', null=True, upload_to='notes_files/'),
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notes_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for page e.g. Page 1', max_length=150, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order/Page Number')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.notes')),
            ],
            options={
                'verbose_name': 'Note Image',
                'verbose_name_plural': 'Note Images',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PYQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the PYQ (e.g. End Sem Exam 2024)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Details / instructions for this paper', null=True)),
                ('file', models.FileField(blank=True, help_text='Upload PYQ PDF or DOCX file', null=True, upload_to='pyq_files/')),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], default='1', max_length=2)),
                ('exam_year', models.IntegerField(default=2024, help_text='e.g. 2023, 2024, 2025')),
                ('cr_name', models.CharField(blank=True, help_text='Uploaded by CR / Contributor', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyqs', to='blog.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyqs', to='blog.course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyqs', to='blog.subject')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyqs', to='blog.academicyear')),
            ],
            options={
                'verbose_name': 'Previous Year Question',
                'verbose_name_plural': 'Previous Year Questions (PYQs)',
                'ordering': ['-exam_year', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PYQImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pyq_images/')),
                ('caption', models.CharField(blank=True, help_text='e.g. Question Paper Page 1', max_length=150, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pyq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.pyq')),
            ],
            options={
                'verbose_name': 'PYQ Image',
                'verbose_name_plural': 'PYQ Images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
