# Generated by Django 5.2.17 on 2026-08-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_inductionprogram_material_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.IntegerField(default=0)),
            ],
        ),
    ]
