# Generated by Django 5.2.17 on 2026-09-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_notes_cr_notes_cr_name_alter_notes_file_noteimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the Assignment (e.g. End Sem Exam 2024)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Details / instructions for this paper', null=True)),
                ('file', models.FileField(blank=True, help_text='Upload Assignment PDF or DOCX file', null=True, upload_to='pyq_files/')),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], default='1', max_length=2)),
                ('author', models.CharField(blank=True, help_text='Uploaded by / Contributor', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='blog.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='blog.course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='blog.subject')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='blog.academicyear')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
