# Generated by Django 5.0.1 on 2026-09-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_pooling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User Name', max_length=100)),
                ('category', models.CharField(choices=[('BUG', 'Bug Report'), ('IDEA', 'Suggestion / Idea'), ('OTHER', 'General Feedback')], default='BUG', max_length=20)),
                ('message', models.TextField(help_text='User Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
