# Generated by Django 5.2.17 on 2026-09-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=5000)),
                ('n_url', models.CharField(blank=True, max_length=5000, null=True)),
                ('icon', models.CharField(help_text='Add lucide icon name.', max_length=200)),
            ],
        ),
    ]
