# Generated by Django 5.2.17 on 2026-09-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='n_url_icon',
            field=models.CharField(blank=True, help_text='Add lucide icon name.', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='n_url_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='icon',
            field=models.CharField(blank=True, help_text='Add lucide icon name.', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
