# Generated by Django 5.2.17 on 2026-09-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_notice_n_url_icon_notice_n_url_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
