# Generated by Django 5.2.17 on 2026-09-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_notice_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('TC', 'Tech Club'), ('SC', 'Sports Club'), ('other', 'Other')])),
                ('group_name', models.CharField(max_length=2000)),
                ('group_dec', models.CharField(max_length=5000)),
                ('group_logo', models.FileField(blank=True, help_text="Upload Group Logo's", null=True, upload_to='group-logo/')),
            ],
        ),
    ]
