# Generated by Django 5.2.17 on 2026-09-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='facebook',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='instagram',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='join',
            field=models.CharField(blank=True, help_text='WhatsApp Group Link', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='linkedin',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
