# Generated by Django 5.2.17 on 2026-09-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_community_facebook_community_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='group_type',
            field=models.CharField(choices=[('TC', 'Tech Club'), ('SC', 'Sports Club'), ('other', 'Other')], max_length=2000),
        ),
    ]
