# Generated by Django 5.2.17 on 2026-09-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_community_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='discord',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='other',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
