# Generated by Django 5.2.17 on 2026-09-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_community_discord_community_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='other_title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
