# Generated by Django 5.2.17 on 2026-09-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_community_other_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, help_text='User Contact', max_length=200),
        ),
        migrations.AlterField(
            model_name='community',
            name='group_type',
            field=models.CharField(choices=[('TC', 'Tech Club'), ('SC', 'Sports Club'), ('SOC', 'Social'), ('other', 'Other')], max_length=2000),
        ),
    ]
