# Generated by Django 5.1.3 on 2026-10-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_feedback_contact_alter_community_group_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="slug",
            field=models.SlugField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
