# Generated by Django 5.0.1 on 2026-10-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_community_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Class Routine Timetable (CSV/Excel)', max_length=150)),
                ('file', models.FileField(help_text='Upload CSV file for Class Routine', upload_to='routine/')),
                ('is_active', models.BooleanField(default=True, help_text='Set as active routine CSV file')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Routine CSV File',
                'verbose_name_plural': 'Class Routine CSV Files',
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
